config/routes.rb
Rails.application.routes.draw do
  get 'members/show'
  devise_for :members, controllers: { registrations: 'registrations' }
  resources :members
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    @member = Member.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_member!, except: %i[index show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order('updated_at DESC')
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_member.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_in_params
    params.require(:member).permit(:email, :username, :remember_me, :password)
  end

  def sign_up_params
    params.require(:member).permit(:email, :username, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:member).permit(:email, :username, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-dark" role='navigation' aria-label='main navigation' >
      <div class="navbar-brand"> 
          <%= link_to root_path, class: 'navbar-item' do %> 
            <h1 class='title is-5 has-text-white'>Members Only</h1>
          <% end %>
          <a role="button" class="navbar-buger" aria-label='menu' data-target='navbar-menu'>
          </a>
          </div>
      </div>

      <div id="navbar-menu" class="navbar-menu">
        <div class="navbar-start">
          <% 
            member = current_member || new_member_session_path
          %>
          <%= link_to member do %>
            <div class="navbar-item">
              <i class="far fa-user fa-2x"></i>
            </div>
          <% end %>
        </div>

        <div class="navbar-end" >
          <div class="navbar-item pr-2">
            <div class="buttons">
              <% if member_signed_in? %>
                <%= link_to 'New Post', new_post_path, class: 'button is-light' %>
                <%= link_to 'Log out', destroy_member_session_path, method: :delete,class: 'button is-light' %>
              <% else %>
                <%= link_to 'Sign up', new_member_registration_path, class: 'button is-light' %>
                <%= link_to 'Log in', new_member_session_path, class: 'button is-light' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/members/show.html.erb
<div class="pt-5" id="feed">
  <article class="media">
    <div class="media-left">
      <figure class="image is-64x64">
        <img src="https://bulma.io/images/placeholders/128x128.png" alt="profile-pic" class="is-rounded">
      </figure>
    </div> 
    <div class="media-content">
      <strong><%= @member.username %></strong> <br>
      <small>Joined on <%= @member.created_at.strftime("%d %B %Y") %> </small><br>
      <small>Has <%= @member.posts.count %> posts</small>
    </div>
    <div class="media-right">
      <%= link_to edit_member_registration_path(@member) do %>
        <div class="icon-text has-text-dark">
          <span class="icon"> <i class="fa fa-user fa-xs"></i></span> 
          <span><small>Edit Profile</small></span>
        </div>
      <% end %>
      <%= link_to member_registration_path(@member), method: :delete do %>
        <div class="icon-text has-text-dark">
          <span class="icon"> <i class="fa fa-trash fa-xs"></i></span> 
          <span><small>Delete Profile</small></span>
        </div>
      <% end %>
    </div>
  </article>

  <div class="pt-3">
    <%= render partial: 'posts/post', collection: @member.posts %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= render "devise/shared/error_messages" %>

<div id="feed">
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |message| %>
      <h3><%= message%></h4>
    <% end %>
  <% end %>
  <%= form_with model: @post  do |f| %>
    <div class="field">
      <%= f.label :title , class: 'label' %>
      <div class="control">
        <%= f.text_field :title, class: 'input', autocomplete: "off", placeholder: 'Title'%>
      </div>
    </div>
    <div class="field">
      <%= f.label :content, class: 'label' %>
      <div class="control">
        <%= f.text_area :content, class: 'textarea is-small', placeholder: 'Your Story', rows: 20 %>
      </div>
    </div>

    <div class="control">
      <%= f.submit 'Post', class: 'button is-dark' %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
  <div class="box">
    <article class="media">
      <div class="media-content">
        <div class="content">
          <strong class="is-size-5"><%= post.title %></strong>
          <br>
          <small class="is-size-7"> 
            <%
              last_updated = post.updated_at.strftime("%B %d, %Y")
              member = post.member
              username = member.username
            %>
            <% if member_signed_in? %>
              <%= link_to username, member_path(member), class: "is-small is-ghost" %> | <%= last_updated %>
            <% end %>
          </small>
          <br>
          <p class="has-text-justified is-size-6" >
            <%= post.content %>
          </p>
        </div> 
      </div> 
    </article>
    <br>
    <% if post.member == current_member %>
      <div class="level-left">
        <div class="level-item">
            <%= link_to edit_post_path(post) do %>
              <span class="icon-text has-text-dark">
                <span class='icon'><i class='fas fa-pen fa-xs' aria-hidden='true'></i></span>
                <span><small>Edit</small></span>
              </span>
            <% end %>
        </div>
        <div class="level-item">
            <%= link_to post, method: :delete do %>
              <span class="icon-text has-text-dark">
              <span class='icon'><i class='fas fa-trash fa-xs' aria-hidden='true'></i></span>
              <span><small>Delete</small></span>
              </span>
            <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="pt-3" id='feed'>
  <%= render partial: 'post', collection: @posts %>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>